export const SelectList = [
  { value: "contains", label: "Contain" },
  { value: "equal", label: "Equal" },
  { value: "starts_with", label: "Starts With" },
  { value: "ends_with", label: "Ends With" },
  // { value: "in", label: "In" },
];
export const NumericSelectList = [
  { value: "contains", label: "Contain" },
  { value: "equal", label: "Equal" },
  { value: "starts_with", label: "Starts With" },
  { value: "ends_with", label: "Ends With" },
  { value: "greater_than", label: "Greater" },
  { value: "between", label: "Between" },
  { value: "less_than", label: "Less" },
  // { value: "in", label: "In" },
];
export const SelectDateList = [
  { value: "greater_than", label: "Greater" },
  { value: "equal", label: "Equal" },
  { value: "between", label: "Between" },
  { value: "less_than", label: "Less" },
];
export const SelectStatusList = [
  { value: "posted", label: "Posted" },
  { value: "save", label: "Save" },
];

export const moduleIconOptions = [
  { value: "fas fa-box", label: "Module" },
  { value: "fas fa-boxes", label: "Submodule" },
  { value: "fas fa-tachometer-alt", label: "Dashboard" },
  { value: "fas fa-list", label: "List" },
  { value: "fas fa-warehouse", label: "Warehouse" },

  { value: "fas fa-user", label: "User" },
  { value: "fas fa-users", label: "Users" },
  { value: "fas fa-cog", label: "Settings" },
  { value: "fas fa-chart-bar", label: "Reports" },
  { value: "fas fa-bell", label: "Notifications" },
  { value: "fas fa-envelope", label: "Messages" },
  { value: "fas fa-sign-out-alt", label: "Logout" },
  { value: "fas fa-home", label: "Home" },
  { value: "fas fa-id-card", label: "Profile" },
  { value: "fas fa-wrench", label: "Tools" },
  { value: "fas fa-shopping-cart", label: "Cart" },
  { value: "fas fa-credit-card", label: "Payments" },
  { value: "fas fa-tasks", label: "Tasks" },
  { value: "fas fa-headset", label: "Support" },
  { value: "fas fa-file", label: "Documents" },
  { value: "fas fa-phone", label: "Contact" },
  { value: "fas fa-user-shield", label: "Admin" },
  { value: "fas fa-heart", label: "Favorites" },
  { value: "fas fa-briefcase", label: "Jobs" },
  { value: "fas fa-plus", label: "Add" },
  { value: "fas fa-trash-alt", label: "Delete" },
  { value: "fas fa-edit", label: "Edit" },
  { value: "fas fa-eye", label: "View" },
  { value: "fas fa-search", label: "Search" },
  { value: "fas fa-check-circle", label: "Success" },
  { value: "fas fa-exclamation-circle", label: "Error" },
  { value: "fas fa-cloud-upload-alt", label: "Upload" },
  { value: "fas fa-download", label: "Download" },
  { value: "fas fa-cogs", label: "Advanced Settings" },
  { value: "fas fa-archive", label: "Archive" },
  { value: "fas fa-map-marker-alt", label: "Location" },
  { value: "fas fa-filter", label: "Filter" },
  { value: "fas fa-share-alt", label: "Share" },
  { value: "fas fa-comment-dots", label: "Feedback" },
  { value: "fas fa-clock", label: "Timer" },
  { value: "fas fa-sliders-h", label: "Preferences" },
  { value: "fas fa-user-plus", label: "Add User" },
  { value: "fas fa-question-circle", label: "Help" },
  { value: "fas fa-lightbulb", label: "Ideas" },
  { value: "fas fa-chart-line", label: "Chart of Accounts" },
  { value: "fas fa-puzzle-piece", label: "Sub Modules" },
  { value: "fas fa-cubes", label: "Modules" },
  { value: "fas fa-building", label: "Department" },
  { value: "fas fa-industry", label: "Companies" },
  { value: "fas fa-wallet", label: "Accounting" },
  { value: "fas fa-anchor", label: "Anchor" },
  { value: "fas fa-apple-alt", label: "Apple" },
  { value: "fas fa-archway", label: "Archway" },
  {
    value: "fas fa-assistive-listening-systems",
    label: "Assistive Listening Systems",
  },
  { value: "fas fa-bacon", label: "Bacon" },
  { value: "fas fa-city", label: "City" },
  { value: "fas fa-balance-scale", label: "Balance Scale" },
  { value: "fas fa-battery-full", label: "Battery Full" },
  { value: "fas fa-bed", label: "Bed" },
  { value: "fas fa-bicycle", label: "Bicycle" },
  { value: "fas fa-binoculars", label: "Binoculars" },
  { value: "fas fa-birthday-cake", label: "Birthday Cake" },
  { value: "fas fa-blender", label: "Blender" },
  { value: "fas fa-bolt", label: "Bolt" },
  { value: "fas fa-bong", label: "Bong" },
  { value: "fas fa-book", label: "Book" },
  { value: "fas fa-bookmark", label: "Bookmark" },
  { value: "fas fa-box-open", label: "Box Open" },
  { value: "fas fa-briefcase-medical", label: "Medical Briefcase" },
  { value: "fas fa-bug", label: "Bug" },
  { value: "fas fa-building", label: "Building" },
  { value: "fas fa-calculator", label: "Accounting" },
  { value: "fas fa-money-bill", label: "Tax" },
  { value: "fas fa-boxes-packing", label: "Supplier" },
  { value: "fas fa-bullhorn", label: "Bullhorn" },
  { value: "fas fa-bus", label: "Bus" },
  { value: "fas fa-calculator", label: "Calculator" },
  { value: "fas fa-camera", label: "Camera" },
  { value: "fas fa-car", label: "Car" },
  { value: "fas fa-cogs", label: "Cogs" },
  { value: "fas fa-comment", label: "Comment" },
  { value: "fas fa-credit-card", label: "Credit Card" },
  { value: "fas fa-crop", label: "Crop" },
  { value: "fa-solid fa-mug-hot", label: "Cup" },
  { value: "fas fa-database", label: "Database" },
  { value: "fas fa-dice", label: "Dice" },
  { value: "fas fa-dolly", label: "Dolly" },
  { value: "fas fa-donate", label: "Donate" },
  { value: "fas fa-drum", label: "Drum" },
  { value: "fas fa-edit", label: "Edit" },
  { value: "fas fa-eye", label: "Eye" },
  { value: "fas fa-fan", label: "Fan" },
  { value: "fas fa-fax", label: "Fax" },
  { value: "fas fa-feather-alt", label: "Feather Alt" },
  { value: "fas fa-female", label: "Female" },
  { value: "fas fa-fire", label: "Fire" },
  { value: "fas fa-fire-extinguisher", label: "Fire Extinguisher" },
  { value: "fas fa-flag", label: "Flag" },
  { value: "fas fa-flask", label: "Flask" },
  { value: "fas fa-folder", label: "Folder" },
  { value: "fas fa-font", label: "Font" },
  { value: "fas fa-football-ball", label: "Football" },
  { value: "fas fa-frown", label: "Frown" },
  { value: "fas fa-gift", label: "Gift" },
  { value: "fas fa-glass-cheers", label: "Glass Cheers" },
  { value: "fas fa-glasses", label: "Glasses" },
  { value: "fas fa-globe", label: "Globe" },
  { value: "fas fa-guitar", label: "Guitar" },
  { value: "fas fa-hat-cowboy", label: "Cowboy Hat" },
  { value: "fas fa-heart", label: "Heart" },
  { value: "fas fa-history", label: "History" },
  { value: "fas fa-home", label: "Home" },
  { value: "fas fa-hospital", label: "Hospital" },
  { value: "fas fa-hotel", label: "Hotel" },
  { value: "fas fa-hat-wizard", label: "Wizard Hat" },
  { value: "fas fa-receipt", label: "Receipt" },
];
